---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-quarkus
spec:
  broker: default
  filter:
    attributes:
      type: quarkusevent
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: svctest1

