apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ubifilepipeline
spec:
  tasks:
    - name: ubifilecreate
      taskRef:
        kind: Task
        name: ubifilecreate
      workspaces:
        - name: working
          workspace: workingarea
    - name: ubifilecheck
      runAfter:
        - ubifilecreate
      taskRef:
        kind: Task
        name: ubifilecheck
      workspaces:
        - name: working
          workspace: workingarea
    - name: ubifileremove
      runAfter:
        - ubifilecheck
      taskRef:
        kind: Task
        name: ubifileremove
      workspaces:
        - name: working
          workspace: workingarea
  workspaces:
    - name: workingarea
