apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: triggeredpipeline
spec:
  params:
    - name: param1
      type: string
      description: Example param 1
    - name: param2
      type: string
      description: Example param 2
  tasks:
    - name: task1
      taskRef:
        name: triggertask1
      params:
        - name: taskparam1
          value: "$(params.param1)"
        - name: taskparam2
          value: "$(params.param2)"
